{"name": "test_contact_us", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected to be 'https://automationexercise.com/'\nActual value: https://automationexercise.com/contact_us#google_vignette \nCall log:\nPageAssertions.to_have_url with timeout 5000ms\nwaiting for locator(\":root\")\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nwaiting for locator(\":root\")\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\n  locator resolved to <html lang=\"en\">…</html>\n  unexpected value \"https://automationexercise.com/contact_us#google_vignette\"", "trace": "self = <tests.test_contact_us.TestContactUs object at 0x00000265985B3FD0>, test_setup = None\n\n    def test_contact_us(self, test_setup):\n        self.contact.check_page_loaded()\n        self.contact.contact_us_btn_click()\n        self.contact.get_in_text_visible()\n        self.contact.set_username(Data.fakeUser)\n        self.contact.set_email(Data.fakeEmail)\n        self.contact.set_subject(Data.subject)\n        self.contact.set_message(Data.message)\n        self.contact.set_upload_file()\n        self.page.wait_for_timeout(1000)\n        self.contact.click_ok()\n        self.contact.submit_btn_click()\n        self.contact.success_msg_visible()\n        self.contact.click_home_btn()\n>       self.contact.check_page_loaded()\n\ntest_contact_us.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.contact_us_page.ContactUs object at 0x0000026598AFDD10>\n\n    def check_page_loaded(self) -> None:\n>       expect(self.page).to_have_url('https://automationexercise.com/')\nE       AssertionError: Page URL expected to be 'https://automationexercise.com/'\nE       Actual value: https://automationexercise.com/contact_us#google_vignette \nE       Call log:\nE       PageAssertions.to_have_url with timeout 5000ms\nE       waiting for locator(\":root\")\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nE       waiting for locator(\":root\")\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\nE         locator resolved to <html lang=\"en\">…</html>\nE         unexpected value \"https://automationexercise.com/contact_us#google_vignette\"\n\n..\\pages\\contact_us_page.py:27: AssertionError"}, "attachments": [{"name": "tests/test_contact_us.py::TestContactUs::test_contact_us.png", "source": "9c6bfb7b-8ea5-4b8d-a7d5-ecc24b3da818-attachment.png", "type": "image/png"}], "start": 1679594956134, "stop": 1679594963338, "uuid": "8e6534d4-aca5-43b1-b21d-f6bb8814a3df", "historyId": "95a616d31375375c8fb98cfc1f895b48", "testCaseId": "24b5e0bcde8364b9384a715f2e9f7b5f", "fullName": "tests.test_contact_us.TestContactUs#test_contact_us", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_contact_us"}, {"name": "subSuite", "value": "TestContactUs"}, {"name": "host", "value": "griddy"}, {"name": "thread", "value": "17356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_contact_us"}]}